In [1]:
import numpy as np

In [ ]:
#FONTOS!!!

# CSAK OTT LEHET HASZNÁLNI FOR LOOP-OT AHOL A FELADAT KÜLÖN KÉRI!
# [1,2,3,4] --> ezek az értékek np.array-ek. Ahol listát kérek paraméterként ott külön ki fogom emelni!
# Ha végeztél a feladatokkal, akkor notebook-ot alakítsd át .py.
# A FÁJLBAN CSAK A FÜGGVÉNYEK LEGYENEK! (KOMMENTEK MARADHATNAK)

In [7]:
# Írj egy olyan fügvényt, ami megfordítja egy 2d array oszlopait. Bemenetként egy array-t vár.
# Be: [[1,2],[3,4]]
# Ki: [[2,1],[4,3]]
# column_swap()

def column_swap(input_array: np.array) -> np.array:
    input_array[:,[1,0]] = input_array[:, [0,1]]
    return input_array

array([[2, 1],
       [4, 3]])

In [10]:
# Készíts egy olyan függvényt ami összehasonlít két array-t és adjon vissza egy array-ben, hogy hol egyenlőek 
# Pl Be: [7,8,9], [9,8,7] 
# Ki: [1]
# compare_two_array()
# egyenlő elemszámúakra kell csak hogy működjön

def compare_two_array(input_array1:np.array, input_array2:np.array) -> np.array:
    result = np.where(input_array1 == input_array2)[0]
    return result


array([1, 3], dtype=int64)

In [20]:
# Készíts egy olyan függvényt, ami vissza adja string-ként a megadott array dimenzióit:
# Be: [[1,2,3], [4,5,6]]
# Ki: "sor: 2, oszlop: 3, melyseg: 1"
# get_array_shape()
# 3D-vel még műküdnie kell!, 

def get_array_shape(input_array:np.array) -> str:
    shape = np.shape(input_array)
    if len(shape) ==1:
        return f"sor: {shape[0]}, oszlop: 1, melyseg: 1"
    if len(shape) ==2:
        return f"sor: {shape[0]}, oszlop: {shape[1]}, melyseg: 1"
    return f"sor: {shape[0]}, oszlop: {shape[1]}, melyseg: {shape[2]}"


In [24]:
# Készíts egy olyan függvényt, aminek segítségével elő tudod állítani egy neurális hálózat tanításához szükséges pred-et egy numpy array-ből. 
# Bementként add meg az array-t, illetve hogy mennyi class-od van. Kimenetként pedig adjon vissza egy 2d array-t, ahol a sorok az egyes elemek. Minden nullákkal teli legyen és csak ott álljon egyes, ahol a bementi tömb megjelöli. 
# Pl. ha 1 van a bemeneten és 4 classod van, akkor az adott sorban az array-ban a [1] helyen álljon egy 1-es, a többi helyen pedig 0.
# Be: [1, 2, 0, 3], 4
# Ki: [[0,1,0,0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1]]
# encode_Y()

def encode_Y(input_array:np.array, classes:int) -> np.array:
    result = np.zeros((len(input_array), classes))
    result[np.arange(len(input_array)),input_array]=1
    return result


array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [25]:
# A fenti feladatnak valósítsd meg a kiértékelését. Adj meg a 2d array-t és adj vissza a decodolt változatát
# Be:  [[0,1,0,0], [0, 0, 1, 0], [1, 0, 0, 0], [0, 0, 0, 1]]
# Ki:  [1, 2, 0, 3]
# decode_Y()


def decode_Y(input_array: np.array) -> np.array:
    return np.argmax(input_array, axis=1)

In [26]:
# Készíts egy olyan függvényt, ami képes kiértékelni egy neurális háló eredményét! Bemenetként egy listát és egy array-t és adja vissza azt az elemet, aminek a legnagyobb a valószínüsége(értéke) a listából.
# Be: ['alma', 'körte', 'szilva'], [0.2, 0.2, 0.6]. # Az ['alma', 'körte', 'szilva'] egy lista!
# Ki: 'szilva'
# eval_classification()

def eval_classification(input_list:list, input_array: np.array) -> str:
    max= np.argmax(input_array)
    return input_list[max]

In [27]:
# Készíts egy olyan függvényt, ahol az 1D array-ben a páratlan számokat -1-re cseréli
# Be: [1,2,3,4,5,6]
# Ki: [-1,2,-1,4,-1,6]
# replace_odd_numbers()

def replace_odd_numbers(input_array:np.array) -> np.array:
    odd_values = (input_array%2 ==1)
    input_array[odd_values]= -1
    return input_array

In [ ]:
# Készíts egy olyan függvényt, ami egy array értékeit -1 és 1-re változtatja, attól függően, hogy az adott elem nagyobb vagy kisebb a paraméterként megadott számnál.
# Ha a szám kisebb mint a megadott érték, akkor -1, ha nagyobb vagy egyenlő, akkor pedig 1.
# Be: [1, 2, 5, 0], 2
# Ki: [-1, 1, 1, -1]
# replace_by_value()

def replace_by_value(input_array: np.array, number: int) -> np.array:
    output = np.where(input_array < number, -1, 1)
    return output

In [29]:
# Készíts egy olyan függvényt, ami egy array értékeit összeszorozza és az eredményt visszaadja
# Be: [1,2,3,4]
# Ki: 24
# array_multi()
# Ha több dimenziós a tömb, akkor az egész tömb elemeinek szorzatával térjen vissza

def array_multi(input_array:np.array) -> int:
    return np.prod(input_array)


In [32]:
# Készíts egy olyan függvényt, ami egy 2D array értékeit összeszorozza és egy olyan array-el tér vissza, aminek az elemei a soroknak a szorzata
# Be: [[1, 2], [3, 4]]
# Ki: [2, 12]
# array_multi_2d()

def array_multi_2d(input_array:np.array) -> np.array:
    return np.prod(input_array,axis=1).reshape(-1)


array([ 2, 12])

In [ ]:
# Készíts egy olyan függvényt, amit egy meglévő numpy array-hez készít egy bordert nullásokkal. Bementként egy array-t várjon és kimenetként egy array jelenjen meg aminek van border-je
# Be: [[1,2],[3,4]]
# Ki: [[0,0,0,0],[0,1,2,0],[0,3,4,0],[0,0,0,0]]
# add_border()

def add_border(input_array:np.array) -> np.array:
    m, n = input_array.shape
    border_array = np.zeros((m+2, n+2))
    border_array[1:-1, 1:-1] = input_array
    return border_array

In [ ]:
# A KÖTVETKEZŐ FELADATOKHOZ NÉZZÉTEK MEG A NUMPY DATA TYPE-JÁT!

In [34]:
# Készíts egy olyan függvényt ami két dátum között felsorolja az összes napot és ezt adja vissza egy numpy array-ben. A fgv ként str vár paraméterként 'YYYY-MM' formában.
# Be: '2023-03', '2023-04'  # mind a kettő paraméter str.
# Ki: ['2023-03-01', '2023-03-02', .. , '2023-03-31',]
# list_days()


def list_days(start_date: str, end_date: str) -> np.array:
    start = np.datetime64(start_date)
    end = np.datetime64(end_date)
    days = np.arange(start, end, dtype='datetime64[D]')
    return days.astype(str)

array(['2023-03-01', '2023-03-02', '2023-03-03', '2023-03-04',
       '2023-03-05', '2023-03-06', '2023-03-07', '2023-03-08',
       '2023-03-09', '2023-03-10', '2023-03-11', '2023-03-12',
       '2023-03-13', '2023-03-14', '2023-03-15', '2023-03-16',
       '2023-03-17', '2023-03-18', '2023-03-19', '2023-03-20',
       '2023-03-21', '2023-03-22', '2023-03-23', '2023-03-24',
       '2023-03-25', '2023-03-26', '2023-03-27', '2023-03-28',
       '2023-03-29', '2023-03-30', '2023-03-31'], dtype='<U28')

In [39]:
# Írj egy fügvényt ami vissza adja az aktuális dátumot az alábbi formában: YYYY-MM-DD. Térjen vissza egy 'numpy.datetime64' típussal.
# Be:
# Ki: 2017-03-24
# get_act_date()

def get_act_date() ->np.datetime64:
    return np.datetime64('today')


In [61]:
# Írj egy olyan függvényt ami visszadja, hogy mennyi másodperc telt el 1970 január 01. 00:02:00 óta. Int-el térjen vissza
# Be: 
# Ki: másodpercben az idó, int-é kasztolva
# sec_from_1970()

def sec_from_1970() -> int:
    start = np.datetime64('1970-01-01T00:02:00')
    now = np.datetime64('now')
    diff = now - start
    return diff.astype('int64')